---
chdir: "/home/ubuntu/ptv_flinders_st"
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: "/home/ubuntu/ptv_flinders_st/log/thin.log"
pid: "/home/ubuntu/ptv_flinders_st/tmp/pids/thin.pid"
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
daemonize: true
